# -*- coding: utf-8 -*-
"""Diabetes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19wMRWCju0is7k6RlaPlpss4zEN6LTDGF
"""

def calculate_bmi(weight, height):
    return weight / ((height / 100) ** 2)

age = int(input("Enter your age: "))
weight = float(input("Enter your weight in kilograms: "))
height = float(input("Enter your height in centimeters: "))
sleep_hours = float(input("Enter your average sleep hours per day: "))
average_glucose = float(input("Enter your average glucose level: "))
family_history = input("Does any family member have diabetes? (yes/no): ")

bmi = calculate_bmi(weight, height)

age_threshold = 50
bmi_threshold = 25
sleep_threshold = 6
glucose_threshold = 110

condition_counter = 0

if age > age_threshold:
    condition_counter += 1
if bmi > bmi_threshold:
    condition_counter += 1
if sleep_hours < sleep_threshold:
    condition_counter += 1
if average_glucose > glucose_threshold:
    condition_counter += 1
if family_history == 'yes':
    condition_counter += 1


if condition_counter >= 4:
    print("highly likely to get diabetes")
elif condition_counter >= 3:
    print("you might get diabetes")
elif condition_counter >= 2:
    print("less likely to get diabetes")
else:
    print("unlikely to get diabetes")